### ISSUE TITLE
Sharing my porting of cspsp to the web

### ISSUE THREAD

**Issue by frankplus** [kevinbchen/cspsp#2]
I would like to share the porting I did of CSPSP to the web:
You can play [here](https://frankplus.github.io/)
Source code is [here](https://github.com/frankplus/csweb)
Right now only offline is working, in order to play online you need to run a proxy and a server which right now I'm not willing to host.

**Comment by vladbondarenko97** [comment]
Yo I really like that ! Why don't we get the online to work and fix some
bugs & maybe increase the size so it's playable.

**Comment by kevinbchen** [comment]
Awesome, this is really cool @frankplus! I did see the port before, but missed this message, so sorry for the super late reply. I've added a link to your repo and page to the readme.
